apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: duckhue01
spec:
  acme:
    email: duckhuejs@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: duckhue01-cluster-ahiho-dev-key
    solvers:
      - http01:
          ingress:
            class: nginx
