apiVersion: v1
kind: Service
metadata:
  name: simple-bank-api-service
  namespace: duckhue01
spec:
  selector:
    app: simple-bank-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
